In [1]:
# 櫃買股票代碼

import requests
import pandas as pd
from io import StringIO

url = "https://isin.twse.com.tw/isin/class_main.jsp?market=2&issuetype=4"
res = requests.get(url)
df = pd.read_html(StringIO(res.text), header = 0)[0] #設定標題欄
df

,頁面編號,國際證券編碼,有價證券代號,有價證券名稱,市場別,有價證券別,產業別,公開發行/上市(櫃)/發行日,CFICode,備註
0,1,TW0001240000,1240,茂生農經,上櫃,股票,農業科技業,2018/08/08,ESVUFR,NaN
1,2,TW0001259000,1259,安心,上櫃,股票,觀光餐旅,2011/12/15,ESVUFR,NaN
2,3,TW0001264000,1264,德麥,上櫃,股票,食品工業,2015/04/09,ESVUFR,NaN
3,4,TW0001268001,1268,漢來美食,上櫃,股票,觀光餐旅,2017/09/27,ESVUFR,NaN
4,5,TW0001294007,1294,漢田生技,上櫃,股票,食品工業,2024/09/26,ESVUFR,NaN
...,...,...,...,...,...,...,...,...,...,...
826,827,TW0009949008,9949,琉園,上櫃,股票,文化創意業,2003/11/21,ESVUFR,NaN
827,828,TW0009950006,9950,萬國通,上櫃,股票,塑膠工業,2004/02/17,ESVUFR,NaN
828,829,TW0009951004,9951,皇田,上櫃,股票,電機機械,2003/12/18,ESVUFR,NaN
829,830,TW0009960005,9960,邁達康,上櫃,股票,運動休閒,2004/12/06,ESVUFR,NaN
830,831,TW0009962001,9962,有益,上櫃,股票,鋼鐵工業,2006/07/10,ESVUFR,NaN

In [3]:
import requests
import pandas as pd
from io import StringIO
import yfinance as yf

data = []  # Initialize as a list to store DataFrames

for i in [1, 4]:
    url = "https://isin.twse.com.tw/isin/class_main.jsp?issuetype={}".format(i)  # 使用 format 函數將 i 代入 URL 中的 {} 區域，動態生成不同的網址
    res = requests.get(url)
    df = pd.read_html(StringIO(res.text), header = 0)[0]  # Set header row
    data.append(df)  # Append DataFrame to the list
df = pd.concat(data, ignore_index=True)

data = []
for idx , row in df.iterrows():
        if row['市場別'] == '上市':
            data.append(str(row['有價證券代號']) + '.tw')
        elif row['市場別'] == '上櫃':
            data.append(str(row['有價證券代號']) + '.two')
df = yf.download(data,"2024-01-01")
df

##	1.	for idx, row in df.iterrows()：這是 Pandas 的一個迴圈方法，會遍歷 df 這個 DataFrame 的每一行資料。idx 是當前行的索引（行號），而 row 是當前行的資料（以 Series 形式表示）。
##	2.	if row['市場別'] == '上市'：這裡檢查當前行的「市場別」欄位是否為「上市」。
##	•	如果「市場別」是「上市」，那麼會將當前行的「有價證券代號」欄位值轉為字串，並加上「.tw」這個字尾後綴，表示它是上市股票的代號格式，然後將結果添加到 data 列表中。
##	3.	elif row['市場別'] == '上櫃'：如果「市場別」是「上櫃」，那麼會將「有價證券代號」加上「.two」這個後綴，表示它是上櫃股票的代號格式，並且同樣將結果添加到 data 列表中。

[*********************100%***********************]  1836 of 1836 completed

Price                      Adj Close                                           \
Ticker                       1101.TW    1102.TW    1103.TW    1104.TW 1108.TW
Date
2024-01-02 00:00:00+00:00  33.685379  41.150002  18.850000  27.622261   15.80
2024-01-03 00:00:00+00:00  33.200001  40.650002  18.700001  27.436253   15.75
2024-01-04 00:00:00+00:00  33.200001  41.150002  18.700001  27.064236   15.80
2024-01-05 00:00:00+00:00  33.345612  41.099998  18.750000  27.343248   15.80
2024-01-08 00:00:00+00:00  33.248539  41.299999  18.799999  27.250244   15.90
...                              ...        ...        ...        ...     ...
2024-10-14 00:00:00+00:00  32.549999  46.000000  17.650000  30.100000   14.50
2024-10-15 00:00:00+00:00  32.500000  46.549999  17.549999  30.049999   14.50
2024-10-16 00:00:00+00:00  32.150002  45.700001  17.500000  31.600000   14.55
2024-10-17 00:00:00+00:00        NaN        NaN        NaN        NaN     NaN
2024-10-18 00:00:00+00:00  32.750000  47.599998  17.799999  30.650000   14.55

Price                                                                  \
Ticker                       1109.TW    1110.TW    1201.TW    1203.TW
Date
2024-01-02 00:00:00+00:00  17.105265  18.799999  19.049999  58.299999
2024-01-03 00:00:00+00:00  17.011278  18.650000  19.049999  57.599998
2024-01-04 00:00:00+00:00  17.058270  18.850000  19.000000  57.000000
2024-01-05 00:00:00+00:00  17.058270  18.799999  19.000000  57.799999
2024-01-08 00:00:00+00:00  17.011278  18.799999  19.000000  57.500000
...                              ...        ...        ...        ...
2024-10-14 00:00:00+00:00  18.400000  22.150000  18.200001  47.500000
2024-10-15 00:00:00+00:00  18.200001  22.200001  18.049999  48.450001
2024-10-16 00:00:00+00:00  18.400000  22.250000  18.049999  47.799999
2024-10-17 00:00:00+00:00        NaN        NaN        NaN        NaN
2024-10-18 00:00:00+00:00  18.400000  22.250000  18.100000  49.549999

Price                                 ...    Volume                       \
Ticker                       1210.TW  ...   9944.TW     9945.TW  9946.TW
Date                                  ...
2024-01-02 00:00:00+00:00  58.900002  ...  129105.0  14973563.0   465181
2024-01-03 00:00:00+00:00  58.799999  ...  114168.0   8563523.0   243376
2024-01-04 00:00:00+00:00  58.200001  ...   85000.0   4541062.0   569216
2024-01-05 00:00:00+00:00  57.599998  ...  116485.0   5381249.0   428000
2024-01-08 00:00:00+00:00  57.799999  ...   56347.0   4496720.0   369101
...                              ...  ...       ...         ...      ...
2024-10-14 00:00:00+00:00  51.799999  ...   98000.0   5459740.0   485100
2024-10-15 00:00:00+00:00  51.900002  ...  103100.0   5055205.0   411354
2024-10-16 00:00:00+00:00  50.500000  ...  123000.0   3900729.0   516763
2024-10-17 00:00:00+00:00        NaN  ...       NaN         NaN   628724
2024-10-18 00:00:00+00:00  51.500000  ...   82000.0   6216974.0  1042269

Price                                                               \
Ticker                     9949.TWO  9950.TWO  9951.TWO    9955.TW
Date
2024-01-02 00:00:00+00:00  195000.0  329000.0  145000.0   171000.0
2024-01-03 00:00:00+00:00   30000.0  358000.0   76000.0   257007.0
2024-01-04 00:00:00+00:00   18000.0  562000.0  136000.0   270637.0
2024-01-05 00:00:00+00:00   69000.0  608000.0  414000.0   158005.0
2024-01-08 00:00:00+00:00   33000.0  279000.0  278000.0   149291.0
...                             ...       ...       ...        ...
2024-10-14 00:00:00+00:00   17000.0   70000.0  103000.0   981548.0
2024-10-15 00:00:00+00:00    9000.0   37000.0   40000.0  1584210.0
2024-10-16 00:00:00+00:00   20000.0   70000.0   62000.0  1223451.0
2024-10-17 00:00:00+00:00       NaN       NaN       NaN        NaN
2024-10-18 00:00:00+00:00   11000.0   58000.0   62000.0  1933242.0

Price
Ticker                        9958.TW 9960.TWO 9962.TWO
Date
2024-01-02 00:00:00+00:00   5217910.0  23000.0   107000
2024-01-03 00:00:00+00:00   3113800.0   7000.0   222000
2024-01-04 00:00:00+00:00   4295062.0  82000.0   200000
2024-01-05 00:00:00+00:00   4637268.0  51000.0   204000
2024-01-08 00:00:00+00:00   2345971.0  24000.0   991000
...                               ...      ...      ...
2024-10-14 00:00:00+00:00   9873282.0  45000.0    98000
2024-10-15 00:00:00+00:00   9013569.0   8000.0    83000
2024-10-16 00:00:00+00:00   7144206.0  30000.0   133000
2024-10-17 00:00:00+00:00         NaN      NaN    77000
2024-10-18 00:00:00+00:00  11803187.0   9000.0    99000

[191 rows x 11016 columns]

In [8]:
# 抓取個股歷史資料

import requests
import pandas as pd
import json
import datetime as dt
from dateutil.relativedelta import relativedelta
import time
import sqlite3 as lite #資料庫套件

#倒數計時

def countdown(t):
    while t > -1:
        min, sec = divmod(t, 60)
        if t > 0:
            print("{:02d}:{:02d}".format(min, sec), end='\r')  # 正確格式化 min 和 sec
        elif t == 0:
            print("{:02d}:{:02d}".format(min, sec), end='\n')  # 倒數結束時換行
        
        t -= 1
        time.sleep(1)

url = "https://www.twse.com.tw/rwd/zh/afterTrading/MI_INDEX"
payload = {
         'date' : '20241018',
        'type' : 'ALLBUT0999',
        'response' : 'json',

}
data = []
#加入日期
base = dt.datetime.today() - relativedelta(years = 0, months = 0, days = 15)  #設定從今天往前抓取的日期範圍
while base < dt.datetime.today():
    payload['date'] = base.strftime("%Y%m%d")
    print(payload['date']) #列印資料進度
    res = requests.get(url, params = payload)
    jd = json.loads(res.text)
    if jd['stat' ] == 'OK': #當交易日stat資料 ＝OK
        td = jd['tables'][8]
        df = pd.DataFrame(td['data'], columns = td['fields'])
        df.insert(0, "日期", jd['date']) #數字 0 表示將新欄位插入為第一個欄位。
        df = df.iloc[:5, :4] #取前五行，前四列
        df = df.apply(lambda x: x.str.replace(',','')) #把逗號取代掉
        data.append(df)
        countdown(15) #每一次抓取後停留15秒
        
    base += relativedelta(days = 1) #以天為單位進行累加
df = pd.concat(data, ignore_index = True)

with lite.connect("每日行情.db") as con:
    df.to_sql("個股每日行情表", con = con, if_exists = 'replace') #如果有存在就覆蓋
df

20241005
20241006
20241007
00:00
20241008
00:00
20241009
00:00
20241010
20241011
00:00
20241012
20241013
20241014
00:00
20241015
00:00
20241016
00:00
20241017
00:00
20241018
00:00
20241019
20241020

          日期  證券代號      證券名稱      成交股數
0   20241007  0050    元大台灣50  13993911
1   20241007  0051   元大中型100     89532
2   20241007  0052      富邦科技    858146
3   20241007  0053      元大電子     29410
4   20241007  0055  元大MSCI金融    186946
5   20241008  0050    元大台灣50   9953432
6   20241008  0051   元大中型100     84788
7   20241008  0052      富邦科技    779010
8   20241008  0053      元大電子      6972
9   20241008  0055  元大MSCI金融     75906
10  20241009  0050    元大台灣50  11860866
11  20241009  0051   元大中型100     70775
12  20241009  0052      富邦科技   1040067
13  20241009  0053      元大電子     18584
14  20241009  0055  元大MSCI金融     69520
15  20241011  0050    元大台灣50  13197709
16  20241011  0051   元大中型100    149180
17  20241011  0052      富邦科技   1028473
18  20241011  0053      元大電子     26128
19  20241011  0055  元大MSCI金融    191260
20  20241014  0050    元大台灣50  10725917
21  20241014  0051   元大中型100    152072
22  20241014  0052      富邦科技    808404
23  20241014  0053      元大電子     27127
24  20241014  0055  元大MSCI金融    102922
25  20241015  0050    元大台灣50  15738243
26  20241015  0051   元大中型100    153006
27  20241015  0052      富邦科技    989205
28  20241015  0053      元大電子     20111
29  20241015  0055  元大MSCI金融    208233
30  20241016  0050    元大台灣50  18604770
31  20241016  0051   元大中型100    115782
32  20241016  0052      富邦科技   1391669
33  20241016  0053      元大電子     14367
34  20241016  0055  元大MSCI金融    153000
35  20241017  0050    元大台灣50   9936801
36  20241017  0051   元大中型100     79858
37  20241017  0052      富邦科技   1016625
38  20241017  0053      元大電子     11398
39  20241017  0055  元大MSCI金融     69019
40  20241018  0050    元大台灣50  33596096
41  20241018  0051   元大中型100    225770
42  20241018  0052      富邦科技   2233354
43  20241018  0053      元大電子     39988
44  20241018  0055  元大MSCI金融    272850

,頁面編號,國際證券編碼,有價證券代號,有價證券名稱,市場別,有價證券別,產業別,公開發行/上市(櫃)/發行日,CFICode,備註
0,1,TW0001240000,1240,茂生農經,上櫃,股票,農業科技業,2018/08/08,ESVUFR,NaN
1,2,TW0001259000,1259,安心,上櫃,股票,觀光餐旅,2011/12/15,ESVUFR,NaN
2,3,TW0001264000,1264,德麥,上櫃,股票,食品工業,2015/04/09,ESVUFR,NaN
3,4,TW0001268001,1268,漢來美食,上櫃,股票,觀光餐旅,2017/09/27,ESVUFR,NaN
4,5,TW0001294007,1294,漢田生技,上櫃,股票,食品工業,2024/09/26,ESVUFR,NaN
...,...,...,...,...,...,...,...,...,...,...
825,826,TW0009949008,9949,琉園,上櫃,股票,文化創意業,2003/11/21,ESVUFR,NaN
826,827,TW0009950006,9950,萬國通,上櫃,股票,塑膠工業,2004/02/17,ESVUFR,NaN
827,828,TW0009951004,9951,皇田,上櫃,股票,電機機械,2003/12/18,ESVUFR,NaN
828,829,TW0009960005,9960,邁達康,上櫃,股票,運動休閒,2004/12/06,ESVUFR,NaN
829,830,TW0009962001,9962,有益,上櫃,股票,鋼鐵工業,2006/07/10,ESVUFR,NaN